{% raw %}---
- name: add nginx ppa
  apt_repository: >
    repo=ppa:nginx/stable
    update_cache=yes
    state=present
  tags:
    - nginx

- name: install nginx package
  apt: >
    pkg=nginx
    update_cache=yes
    cache_valid_time={{six_hours}}
    state=latest
  sudo: True
  tags:
    - nginx

- name: remove default nginx site
  file: >
    path=/etc/nginx/sites-enabled/default
    state=absent
  tags:
    - nginx

- name: write nginx.conf
  template: >
    src=nginx.j2
    dest=/etc/nginx/nginx.conf
    validate="nginx -t -c %s"
  tags:
    - nginx

- name: add vhost config to sites-available
  template: >
    src=nginx_vhost.j2
    dest=/etc/nginx/sites-available/{{project_name}}.conf
  tags:
    - nginx

- name: symlink nginx site conf to sites-enabled
  file: >
    src=/etc/nginx/sites-available/{{project_name}}.conf
    dest=/etc/nginx/sites-enabled/{{project_name}}.conf
    state=link
  tags:
    - nginx

- name: stop nginx
  service: name=nginx state=stopped
  tags:
    - nginx

- name: start nginx
  service: name=nginx state=started
  tags:
    - nginx{% endraw %}
