---
fqdn: localhost
root_user: vagrant
{% raw %}
# postgres
postgres_user_name: "pg_{{ project_name }}"
postgres_db_name: "db_{{ project_name }}"
postgres_password: password
{% endraw %}

# rabbitmq
rabbitmq_user: django
rabbitmq_password: changeme
rabbit_node: rabbit@{{cookiecutter.repo_name}}

reqs_file: local.txt

is_production: False

{% raw %}
env_vars:
  DJANGO_SETTINGS_MODULE: config.settings
  DJANGO_CONFIGURATION: Local
  DATABASE_URL: "postgres://{{ postgres_user_name }}:{{ postgres_password }}@localhost:5432/{{ postgres_db_name }}"
  RABBITMQ_URL: "amqp://{{ rabbitmq_user }}:{{ rabbitmq_password }}@localhost:5672//{{ project_name }}"
{% endraw %}
