{% raw %}---
- name: copy /.ssh/config
  copy: src=ssh_config dest=/home/{{ django_user }}/.ssh/config owner={{django_user}} group={{django_user}}
  tags:
    - deploy

- name: "ensure ~/.virtualenvs/{{project_name}} dir is created"
  file: path={{ virtualenv_dir }} state=directory
  tags:
    - deploy

# shouldn't be needed, already set permissions when creating dir
# check if works without
# - name: "ensure correct permission in /var/log/{{project_name}}"
#   command: "{{ item }}"
#   with_items:
#     - "chown --recursive {{ django_user }}:www-data /var/log/{{ project_name }}"
#     - "chmod --recursive 775 /var/log/{{ project_name }}"
#   tags:
#     - deploy

- name: ensure correct permissions on virtualenv dir
  file: >
    path={{ virtualenv_dir }}
    recurse=yes
    state=directory
    owner={{ django_user }}
    group=www-data
  tags:
    - deploy

- name: ensure correct permissions on code_root_dir dir
  file: >
    path={{ code_root_dir }}
    recurse=yes
    state=directory
    owner={{ django_user }}
    group=www-data
  tags:
    - deploy

- name: pull git
  git: >
    repo={{ git_repo }}
    dest={{ code_root_dir }}
    accept_hostkey=yes
    key_file=/home/{{ django_user }}/.ssh/id_rsa
  update: True
  sudo: False
  when: is_production
  tags:
    - deploy

- name: install pip requirements
  pip: >
    virtualenv={{ virtualenv_dir }}
    requirements={{ reqs_dir }}/{{ reqs_file }}
  tags:
    - deploy

- name: run django manage commands
  django_manage: >
    app_path={{ django_root_dir }}
    command={{ item }}
    settings={{ settings_module }}
    virtualenv={{ virtualenv_dir }}
  with_items:
    - syncdb
    - migrate
    - collectstatic
  tags:
    - deploy
  environment: env_vars

- name: "restart supervisor managed processes"
  supervisorctl: name={{ item }} state=restarted
  with_items:
    - "{{ project_name }}"
    # - celerybeat
    # - celeryd
  sudo: True
  tags:
    - deploy{% endraw %}
