{% raw %}---
- name: copy /.ssh/config
  copy: >
    src=ssh_config
    dest=/home/{{ django_user }}/.ssh/config
    owner={{django_user}}
    group={{django_user}}
  tags:
    - deploy

- name: "ensure /home/{{ django_user }}/.virtualenvs/ dir is created"
  file: >
    path=/home/{{ django_user }}/.virtualenvs
    recurse=yes
    owner={{ django_user }}
    group=www-data
    state=directory
   tags:
     - deploy

- name: ensure correct permissions on code_root_dir dir
  file: >
    path={{ code_root_dir }}
    recurse=yes
    owner={{ django_user }}
    group=www-data
    state=directory
  tags:
    - deploy

- name: pull git
  git: >
    repo={{ git_repo }}
    dest={{ code_root_dir }}
    accept_hostkey=yes
    key_file=/home/{{ django_user }}/.ssh/id_rsa
    update=yes
  sudo: False
  when: is_production
  tags:
    - deploy

- name: install pip requirements
  pip: >
    virtualenv={{ virtualenv_dir }}
    requirements={{ reqs_dir }}/{{ reqs_file }}
  tags:
    - deploy

- name: run django manage commands
  django_manage: >
    app_path={{ django_root_dir }}
    command={{ item }}
    settings={{ settings_module }}
    virtualenv={{ virtualenv_dir }}
  with_items:
    - syncdb
    - migrate
    - collectstatic
  tags:
    - deploy
  environment: env_vars

- name: "restart supervisor managed processes"
  supervisorctl: >
    name={{ item }}
    state=restarted
  with_items:
    - "{{ project_name }}"
    # - celerybeat
    # - celeryd
  sudo: True
  tags:
    - deploy{% endraw %}
