{% raw %}---
- name: "install Redis server: {{redis_package}}"
  apt: >
    pkg={{redis_package}}
    update_cache=yes
    cache_valid_time={{six_hours}}
    state=installed
  tags:
    - redis

- name: bind Redis server to all interfaces
  lineinfile: >
    dest=/etc/redis/redis.conf
    regexp="^#?bind"
    line="#bind 127.0.0.1"
    state=present
  notify:
    - restart Redis
  tags:
    - redis

- name: ensure Redis server is running
  service: >
    name={{redis_package}}
    state=started
  tags:
    - redis

- name: install Redmon dependencies
  apt: >
    pkg={{item}}
    update_cache=yes
    cache_valid_time={{six_hours}}
    state=installed
  with_items: redmon_dependencies
  when: install_redmon
  tags:
    - redis

- name: set Ruby 1.9.1 (ABI version) as default
  command: update-alternatives --set ruby /usr/bin/ruby1.9.1
  when: install_redmon
  tags:
    - redis

- name: set gem to corresponding Ruby version
  command: update-alternatives --set gem /usr/bin/gem1.9.1
  when: install_redmon
  tags:
    - redis

- name: install gems requered for Redmon
  gem: >
    name={{item}}
    state=present
  with_items: redmon_gems
  sudo: False
  tags:
    - redis

- name: "link {{redmon_service}} to /usr/local/bin"
  file: >
    src=/home/vagrant/.gem/ruby/1.9.1/bin/redmon
    dest=/usr/local/bin/redmon
    state=link
  when: install_redmon
  tags:
    - redis

# - name: Redmon supervisord conf file
#   template: src=redmon.j2 dest=/etc/supervisor/{{redmon_service}}.conf  owner=root group=root mode='755'
#   when: install_redmon
#   tags:
#     - redis

# - name: ensure Redmon server is running
#   supervisorctl: name={{redmon_service}} state=started
#   when: install_redmon
#   tags:
#     - redis{% endraw %}
